lang: fr

project: 
  title: "l'avenir durable"
  type: website
  output-dir: docs/fr

website:
  page-navigation: true
  title: "Accueil"
  site-url: "https://sustainable-future.ca/"
  page-footer:
    left: "Cite web créer avec [Quarto](https://quarto.org/) par [Kunal](https://ilovesoils.com/about.html)."

    right:
      - text: English
        href: https://sustainable-future.ca/index.html
      - text: Français
        href: https://sustainable-future.ca/fr/index.html
      - icon: envelope
        href: mailto:info@ilovesoils.com
    
    center: |
      @2024 l'avenir durable. <br>
       Tous droits reservés.
       
  navbar:
    left:
      - text: "À propos"
        href: about.qmd
      - text: "Nos Services"
        href: services.qmd 
      - text: "Emplois"
        href: careers.qmd
      - text: "Collaborateurs"
        href: "collaborators.qmd"       
      - text: "Pourquoi nous choisir?"
        href: choose.qmd
      - text: "Nous Contacter"
        href: contact2.qmd
    right:
      - href: https://sustainable-future.ca/index.html
        text: English
      - href: https://sustainable-future.ca/fr/index.html
        text: Français 
