lang: fr

project: 
  title: "l'avenir durable"
  type: website
  output-dir: docs/fr

website:
  favicon: images\logo.jpg
  page-navigation: true
  title: "Avenir Durable"
  site-url: "https://sustainable-future.ca/"
  page-footer:
    left: 
      - text: Éthique
        href: ethics.qmd
      - text: Politique de confidentialité
        href: policy.qmd
      - text: Conditions de service
        href: terms.qmd

    right:
      - text: English
        href: https://sustainable-future.ca/index.html
      - text: Français
        href: https://sustainable-future.ca/fr/index.html
      - icon: envelope
        href: mailto:info@sustainable-future.ca
    
    center: |
      @2024 l'avenir durable. <br>
       Tous droits reservés. <br>
       Cite web créer avec [Quarto](https://quarto.org/) par [Kunal](https://ilovesoils.com/about.html).
       
  navbar:
    left:
      - text: "À propos"
        href: about.qmd
      - text: "Nos Services"
        href: services.qmd 
      - text: "Emplois"
        href: careers.qmd
      - text: "Collaborateurs"
        href: "collaborators.qmd"       
      - text: "Pourquoi nous choisir?"
        href: choose.qmd
      - text: "Nous Contacter"
        href: contact2.qmd
    right:
      - href: https://sustainable-future.ca/index.html
        text: English
      - href: https://sustainable-future.ca/fr/index.html
        text: Français 
format:
  html:
    theme: 
      light: cerulean
      dark: cyborg
    fontsize: 1.1em
    linestretch: 1.7
    css: styles.css
    toc: true