project:
  type: website
  output-dir: docs
  #post-render: _post-render.py
  preview:
    port: 4200


#profile:
  #default: english
  #group: 
  #  - [english, français]

metadata-files: 
  - _quarto-french.yml
  - _quarto-english.yml

format:
  html:
    theme: journal
    css: styles.css
    toc: true

